# Generated by Django 5.2.4 on 2025-07-30 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_location', models.CharField(help_text='Primary office location for this administrator', max_length=100)),
                ('last_access', models.DateTimeField(auto_now=True, help_text='Last time this admin accessed the system')),
                ('admin', models.OneToOneField(help_text='The user account associated with this admin', on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(blank=True, choices=[('level1', 'Level 1 - Basic'), ('level2', 'Level 2 - Intermediate'), ('level3', 'Level 3 - Advanced'), ('specialist', 'Specialist')], help_text="Inspector's certification level or qualification", max_length=100)),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Number of years of inspection experience')),
                ('inspector', models.OneToOneField(help_text='The user account associated with this inspector', on_delete=django.db.models.deletion.CASCADE, related_name='inspector_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-years_of_experience', 'qualification'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('production', 'Production'), ('maintenance', 'Maintenance'), ('quality', 'Quality Control'), ('shipping', 'Shipping/Receiving'), ('other', 'Other')], help_text='Department the worker is assigned to', max_length=100)),
                ('shift_type', models.CharField(choices=[('day', 'Day Shift (8am-4pm)'), ('evening', 'Evening Shift (4pm-12am)'), ('night', 'Night Shift (12am-8am)'), ('rotation', 'Rotating Shifts')], default='day', help_text="The worker's regular shift schedule", max_length=20)),
                ('shift_time', models.TimeField(blank=True, help_text="Time when the worker's shift starts (if applicable)", null=True)),
                ('next_shift_start', models.DateTimeField(blank=True, help_text="Date and time of worker's next scheduled shift", null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this worker is currently active')),
                ('hire_date', models.DateField(blank=True, help_text='Date when the worker was hired', null=True)),
                ('worker', models.OneToOneField(help_text='The user account associated with this worker', on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department', 'shift_type'],
            },
        ),
    ]
