# Generated by Django 5.2.1 on 2025-08-03 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspector',
            options={},
        ),
        migrations.RemoveField(
            model_name='admin',
            name='last_access',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='is_active',
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Date and time when the client registered')),
                ('client', models.OneToOneField(help_text='The user account associated with this client', on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_joined'],
            },
        ),
    ]
