# Generated by Django 5.2.1 on 2025-08-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_inspector_options_remove_admin_last_access_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Age of the client (if applicable, e.g., for individual clients)', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, help_text="Name of the client's company or organization", max_length=100, null=True),
        ),
    ]
