# Generated by Django 5.2.1 on 2025-08-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certifications',
            field=models.TextField(blank=True, help_text='List of certifications or qualifications held by the inspector', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, choices=[('level1', 'Level 1 - Basic'), ('level2', 'Level 2 - Intermediate'), ('level3', 'Level 3 - Advanced'), ('specialist', 'Specialist')], help_text="Inspector's certification level or qualification", max_length=100),
        ),
    ]
