# Generated by Django 5.2.1 on 2025-08-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_certifications_user_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('inspector', 'Inspector'), ('worker', 'Worker'), ('client', 'Client')], max_length=20),
        ),
    ]
