# Generated by Django 5.2.1 on 2025-08-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_certifications_remove_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(default='Unique Care limited Network', max_length=100),
        ),
    ]
