# Generated by Django 5.2.1 on 2025-08-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
    ]
