# Generated by Django 5.2.4 on 2025-07-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_firealarmweeklyinspection_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinspection',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='baseinspection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
