# Generated by Django 5.2.4 on 2025-07-31 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_alter_baseinspection_approval_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirstAidChecklist',
            new_name='FirstAidChecklistInspection',
        ),
    ]
