# Generated by Django 5.2.4 on 2025-07-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_rename_firstaidchecklist_firstaidchecklistinspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstaidchecklistinspection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
