# Generated by Django 5.2.4 on 2025-07-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_firstaidchecklistinspection_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthsafetychecklist',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this checklist active?'),
        ),
    ]
