# Generated by Django 5.2.4 on 2025-07-31 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_healthsafetychecklist_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationAuditComprehensiveInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Full name of the client being audited', max_length=100)),
                ('client_id', models.CharField(help_text='Unique identifier for the client', max_length=50)),
                ('date_of_audit', models.DateField(help_text='Date when the medication audit was conducted')),
                ('auditor_name', models.CharField(help_text='Name of the person conducting the audit', max_length=100)),
                ('medications_cabinet_securely_locked', models.BooleanField(default=False, help_text='Is the medication cabinet securely locked?')),
                ('medication_cabinet_clean_no_spillages', models.BooleanField(default=False, help_text='Is the medication cabinet clean with no spillages?', verbose_name='Medication Cabinet Clean')),
                ('medications_have_opening_dates_original_labels', models.BooleanField(default=False, help_text='Do all medications have opening dates and original labels?', verbose_name='Proper Medication Labeling')),
                ('medication_label_has_client_details', models.BooleanField(default=False, help_text='Do medication labels include client details?')),
                ('medication_stored_correctly', models.BooleanField(default=False, help_text='Are all medications stored correctly according to requirements?')),
                ('current_marr_sheet_match_client_records', models.BooleanField(default=False, help_text='Does the current MARR sheet match client records?', verbose_name='MARR Sheet Accuracy')),
                ('marr_sheet_list_all_medications_prescribed', models.BooleanField(default=False, help_text='Does the MARR sheet list all prescribed medications?', verbose_name='Complete MARR Sheet')),
                ('gap_on_marr_sheet', models.BooleanField(default=False, help_text='Are there any gaps in the MARR sheet documentation?')),
                ('all_documentation_black_ink', models.BooleanField(default=False, help_text='Is all documentation completed in black ink?')),
                ('control_drug_for_client', models.BooleanField(default=False, help_text='Are there any controlled drugs for this client?', verbose_name='Controlled Drugs Present')),
                ('controlled_drugs_stored_recorded_correctly_count_correct', models.BooleanField(default=False, help_text='Are controlled drugs stored, recorded, and counted correctly?', verbose_name='Controlled Drugs Properly Managed')),
                ('prn_medications', models.BooleanField(default=False, help_text='Are there any PRN (as-needed) medications?', verbose_name='PRN Medications Present')),
                ('directives_for_prn_clear_comprehensive', models.BooleanField(default=False, help_text='Are directives for PRN medications clear and comprehensive?', verbose_name='Clear PRN Directives')),
                ('medications_administration_coded_on_marr_sheet', models.BooleanField(default=False, help_text='Are medication administrations properly coded on MARR sheet?', verbose_name='Proper Administration Coding')),
                ('records_of_refusal_gp_informed', models.BooleanField(default=False, help_text='Are there records of medication refusal and GP notification?')),
                ('transdermal_patch_protocol_for_use', models.BooleanField(default=False, help_text='Is there a protocol for transdermal patch use?')),
                ('client_take_any_blood_thinners_up_to_date_risk_assessment', models.BooleanField(default=False, help_text='Is there an up-to-date risk assessment for blood thinners?', verbose_name='Blood Thinner Risk Assessment')),
                ('order_of_medication_done_monthly_basis', models.BooleanField(default=False, help_text='Is medication ordering done on a monthly basis?', verbose_name='Monthly Medication Orders')),
                ('returns_medication_recorded_correctly_returns_book', models.BooleanField(default=False, help_text='Are medication returns recorded correctly in the returns book?', verbose_name='Proper Medication Returns')),
                ('missing_administration_why', models.TextField(blank=True, help_text='Explanation for any missing administrations', null=True)),
                ('why_returns_medication_for_client', models.TextField(blank=True, help_text='Reason for medication returns for this client', null=True)),
                ('any_additional_comments', models.TextField(blank=True, help_text='Any additional comments about the medication audit', null=True)),
                ('any_follow_up_requires_by_whom', models.TextField(blank=True, help_text='Details of any required follow-up and responsible parties', null=True)),
                ('staff_name', models.CharField(help_text='Name of staff member completing the audit', max_length=100)),
                ('staff_signature', models.CharField(help_text='Signature of staff member completing the audit', max_length=100)),
                ('comments', models.TextField(blank=True, help_text='General comments about the audit', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the audit is active or has been soft deleted')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medication_audit_comprehensive', to='inspections.baseinspection', verbose_name='Related Inspection')),
            ],
            options={
                'verbose_name': 'Comprehensive Medication Audit',
                'verbose_name_plural': 'Comprehensive Medication Audits',
                'ordering': ['-date_of_audit', 'client_name'],
            },
        ),
    ]
