# Generated by Django 5.2.4 on 2025-08-02 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_medicationauditcomprehensiveinspection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firealarmweeklyinspection',
            name='staff_signature_check',
        ),
        migrations.RemoveField(
            model_name='firstaidchecklistinspection',
            name='date_of_inspection',
        ),
        migrations.CreateModel(
            name='SmokeAlarmWeeklyInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, help_text='Location of the smoke alarm being inspected', max_length=255, null=True)),
                ('installed_condition_ok', models.BooleanField(default=False, help_text='Is the smoke alarm properly installed and in good condition?', verbose_name='Installation Condition OK')),
                ('alarm_functional', models.BooleanField(default=False, help_text='Is the smoke alarm functioning correctly?', verbose_name='Alarm Functional')),
                ('battery_replaced', models.BooleanField(default=False, help_text='Has the battery been replaced as needed?')),
                ('faults_identified', models.TextField(blank=True, help_text='Description of any faults found during inspection', null=True, verbose_name='Identified Faults')),
                ('action_taken', models.TextField(blank=True, help_text='Corrective actions taken to address identified faults', null=True)),
                ('management_book_initials', models.CharField(blank=True, help_text='Initials in the management book confirming inspection', max_length=10, null=True)),
                ('comments', models.TextField(blank=True, help_text='Additional comments about the smoke alarm inspection', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smoke_alarm_weekly', to='inspections.baseinspection')),
            ],
        ),
        migrations.DeleteModel(
            name='SmokeAlarmWeekly',
        ),
    ]
