# Generated by Django 5.2.1 on 2025-08-02 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_remove_firealarmweeklyinspection_staff_signature_check_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMedicationAuditInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('client_name', models.CharField(help_text='Full name of the client being audited', max_length=255)),
                ('client_id', models.CharField(help_text='Unique identifier for the client', max_length=100)),
                ('date_of_audit', models.DateField(help_text='Date when the medication audit was conducted')),
                ('auditor_name', models.CharField(help_text='Name of the person conducting the audit', max_length=255)),
                ('medications_cabinet_securely_locked', models.BooleanField(default=False, help_text='Is the medication cabinet securely locked?')),
                ('medication_cabinet_clean_no_spillages', models.BooleanField(default=False, help_text='Is the medication cabinet clean with no spillages?', verbose_name='Medication Cabinet Clean')),
                ('medications_have_opening_dates_original_labels', models.BooleanField(default=False, help_text='Do all medications have opening dates and original labels?', verbose_name='Proper Medication Labeling')),
                ('medication_label_has_client_details', models.BooleanField(default=False, help_text='Do medication labels include client details?')),
                ('medication_stored_correctly', models.BooleanField(default=False, help_text='Are all medications stored correctly according to requirements?')),
                ('current_marr_sheet_match_client_records', models.BooleanField(default=False, help_text='Does the current MARR sheet match client records?', verbose_name='MARR Sheet Accuracy')),
                ('marr_sheet_list_all_medications_prescribed', models.BooleanField(default=False, help_text='Does the MARR sheet list all prescribed medications?', verbose_name='Complete MARR Sheet')),
                ('gap_on_marr_sheet', models.BooleanField(default=False, help_text='Are there any gaps in the MARR sheet documentation?')),
                ('boxed_bottled_medications_stock_count_entered', models.BooleanField(default=False, help_text='Are stock counts entered for boxed/bottled medications?', verbose_name='Stock Count Entered')),
                ('all_documentation_black_ink', models.BooleanField(default=False, help_text='Is all documentation completed in black ink?')),
                ('control_drug_for_client', models.BooleanField(default=False, help_text='Are there any controlled drugs for this client?', verbose_name='Controlled Drugs Present')),
                ('controlled_drugs_stored_recorded_correctly_count_correct', models.BooleanField(default=False, help_text='Are controlled drugs stored, recorded, and counted correctly?', verbose_name='Controlled Drugs Properly Managed')),
                ('prn_medications', models.BooleanField(default=False, help_text='Are there any PRN (as-needed) medications?', verbose_name='PRN Medications Present')),
                ('directives_for_prn_clear_comprehensive', models.BooleanField(default=False, help_text='Are directives for PRN medications clear and comprehensive?', verbose_name='Clear PRN Directives')),
                ('medication_count_accurate', models.BooleanField(default=False, help_text='Is the medication count accurate?')),
                ('medication_expiry_checked', models.BooleanField(default=False, help_text='Have medication expiry dates been checked?')),
                ('missing_administration_why', models.TextField(blank=True, help_text='Explanation for any missing administrations', null=True, verbose_name='Missing Administration Reason')),
                ('any_issues', models.TextField(blank=True, help_text='Any issues identified during the audit', null=True)),
                ('staff_signature', models.CharField(help_text='Signature of staff member completing the audit', max_length=255)),
                ('comments', models.TextField(blank=True, help_text='Additional comments about the audit', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this audit record was created')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_medication_audit', to='inspections.baseinspection')),
            ],
            options={
                'verbose_name': 'Weekly Medication Audit',
                'verbose_name_plural': 'Weekly Medication Audits',
                'ordering': ['-date_of_audit', 'client_name'],
            },
        ),
        migrations.DeleteModel(
            name='WeeklyMedicationAudit',
        ),
    ]
