# Generated by Django 5.2.1 on 2025-08-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_weeklymedicationauditinspection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklymedicationauditinspection',
            options={'ordering': ['-inspection__inspection_type', '-inspection__created_at'], 'verbose_name': 'Weekly Medication Audit', 'verbose_name_plural': 'Weekly Medication Audits'},
        ),
        migrations.RemoveField(
            model_name='weeklymedicationauditinspection',
            name='auditor_name',
        ),
        migrations.RemoveField(
            model_name='weeklymedicationauditinspection',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='weeklymedicationauditinspection',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='weeklymedicationauditinspection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='weeklymedicationauditinspection',
            name='date_of_audit',
        ),
    ]
