# Generated by Django 5.2.1 on 2025-08-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0010_alter_weeklymedicationauditinspection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklymedicationauditinspection',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this audit active?'),
        ),
    ]
