# Generated by Django 5.2.1 on 2025-08-02 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0011_weeklymedicationauditinspection_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicationauditcomprehensiveinspection',
            options={'ordering': ['-inspection__created_at', 'client_name'], 'verbose_name': 'Comprehensive Medication Audit', 'verbose_name_plural': 'Comprehensive Medication Audits'},
        ),
        migrations.RemoveField(
            model_name='medicationauditcomprehensiveinspection',
            name='auditor_name',
        ),
        migrations.RemoveField(
            model_name='medicationauditcomprehensiveinspection',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='medicationauditcomprehensiveinspection',
            name='date_of_audit',
        ),
        migrations.RemoveField(
            model_name='medicationauditcomprehensiveinspection',
            name='staff_name',
        ),
        migrations.RemoveField(
            model_name='medicationauditcomprehensiveinspection',
            name='staff_signature',
        ),
        migrations.AlterField(
            model_name='firealarmweeklyinspection',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_alarm_weekly', to='inspections.baseinspection'),
        ),
        migrations.AlterField(
            model_name='firstaidchecklistinspection',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_aid_checklists', to='inspections.baseinspection'),
        ),
        migrations.AlterField(
            model_name='healthsafetychecklist',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_safety_checklists', to='inspections.baseinspection'),
        ),
        migrations.AlterField(
            model_name='medicationauditcomprehensiveinspection',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_audit_comprehensives', to='inspections.baseinspection'),
        ),
        migrations.AlterField(
            model_name='smokealarmweeklyinspection',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smoke_alarm_weekly', to='inspections.baseinspection'),
        ),
        migrations.AlterField(
            model_name='weeklymedicationauditinspection',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_medication_audits', to='inspections.baseinspection'),
        ),
    ]
