# Generated by Django 5.2.1 on 2025-08-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0012_alter_medicationauditcomprehensiveinspection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicationauditcomprehensiveinspection',
            options={'ordering': ['-inspection__created_at', '-inspection__client_name'], 'verbose_name': 'Comprehensive Medication Audit', 'verbose_name_plural': 'Comprehensive Medication Audits'},
        ),
        migrations.AlterModelOptions(
            name='weeklymedicationauditinspection',
            options={'ordering': ['-inspection__created_at'], 'verbose_name': 'Weekly Medication Audit', 'verbose_name_plural': 'Weekly Medication Audits'},
        ),
        migrations.RemoveField(
            model_name='baseinspection',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='medicationauditcomprehensiveinspection',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='smokealarmweeklyinspection',
            name='location',
        ),
        migrations.RemoveField(
            model_name='weeklymedicationauditinspection',
            name='location',
        ),
        migrations.AddField(
            model_name='baseinspection',
            name='client_name',
            field=models.CharField(blank=True, help_text='Full name of the client being audited', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='baseinspection',
            name='location',
            field=models.CharField(blank=True, help_text='Location of the smoke alarm being inspected', max_length=255, null=True),
        ),
    ]
