# Generated by Django 5.2.1 on 2025-08-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0013_alter_medicationauditcomprehensiveinspection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthsafetychecklist',
            name='location',
        ),
    ]
