# Generated by Django 5.2.1 on 2025-08-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0014_remove_healthsafetychecklist_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklymedicationauditinspection',
            name='staff_signature',
        ),
    ]
