# Generated by Django 5.2.1 on 2025-08-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0015_remove_weeklymedicationauditinspection_staff_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinspection',
            name='submitted_by_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('inspector', 'Inspector'), ('worker', 'Worker'), ('client', 'Client')], max_length=20),
        ),
    ]
