# Generated by Django 5.2.4 on 2025-08-11 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0016_alter_baseinspection_submitted_by_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firealarmweeklyinspection',
            name='location',
        ),
    ]
