# Generated by Django 5.2.4 on 2025-08-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0017_remove_firealarmweeklyinspection_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firealarmweeklyinspection',
            name='alarm_functional',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='firealarmweeklyinspection',
            name='call_points_accessible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='firealarmweeklyinspection',
            name='emergency_lights_working',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
