# Generated by Django 5.2.1 on 2025-09-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0018_alter_firealarmweeklyinspection_alarm_functional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firealarmweeklyinspection',
            name='management_book_initials',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
